# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Promotion' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'WeexSDK', '~>0.18.0'
pod 'WeexPluginLoader'
pod 'SDWebImage', '3.7.5'
pod 'SVProgressHUD' , '2.1.2'
end
